version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    links:
      - mysql-db
    build: .
    restart: always
    env_file: ./.env
    ports:
      - 80:80
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port" : "80",
        "spring.datasource.url"  : "jdbc:mysql://mysql-db/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: